### PR TITLE
Fix IP range logic

### LINKED ISSUE #667: Fatal error: Allowed memory size exhausted during AutoScan #255
Application crashes with an out of memory error when attempting an AutoScan spanning accross multiple subnets.
It was discovered because an user error when inputing the range, but it would be nice to validate the user input or protect the application from crashing.

## Expected Behavior
Receive an "unsupported" notification if range in AutoScan spans accros multiple subnets or something else preventing the exception to be shown to user and alerting about the mistake.

## Current Behavior
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 149

@inverse, even setting the log level in the addon to trace, I don't have any output in the addon log in HomeAssistant. Any ideas how I can extract the full stack?

## Steps to Reproduce
Open the interface and select Autoscan.
Select from IP as 192.168.44.1
Select To IP as 192.168.66.254

## Context (Environment)
HomeAssitant OS running on Raspi 4 4GB
TasmoAdmin Addon 0.20.0

### PR DESCRIPTION
**Pull request by inverse**
Limit the max amount of IPs to be scanned to 1024 whilst also fixing the IP range logic by leveraging PHP's built in functionality.

image

Resolves #667

### CODE REVIEW

**Comment by alexdelprete** [comment]
So what is the max limit? We can't scan a single subnet like the one in the screenshot with 254 hosts?

**Comment by alexdelprete** [comment]
If the limit is 1024, why do I see in the screenshot an error msg for `192.168.1.1` to `192.168.2.254`? It's 254 hosts...well, in reality we'd need to check the subnet mask...:)

**Comment by inverse** [comment]
was when i was playing around with it.

yeah perhaps i should batch the searching. will see what i can do!

**Comment by alexdelprete** [comment]
I think a class C subnet (254 hosts) is more than enough. who has all those devicea?

if on different subnets, they can search one at a time.

**Pull request merged**
