### PR TITLE
Handle minimal firmware properly

### LINKED ISSUE #633: Removal of minimal firmware handling
When redoing `device_update.js` in the 2.1.0 releases I noticed that the handling for minimal firmwares as never called. See: https://github.com/TasmoAdmin/TasmoAdmin/blob/ea332c5edbf16e59b621bf3361ad8f51fb398b7e/tasmoadmin/resources/js/device_update.js#L21

Should this be removed completely since it serves no purpose currently? Or should it handled correctly? If so what was the intended flow for that? 

cc @alexdelprete @reloxx13

### PR DESCRIPTION
**Pull request by inverse**
- Remove gzip setting since automatic always uses gzip
- For manual require it
- Clean up manual firmware elements since it's dependant on filename

Resolves #633

### CODE REVIEW

**Comment by inverse** [comment]
@alexdelprete this one is making me go a bit crazy :D For some reason updates seem to not succeed with this and i'm not sure what I've done wrong.

I first set `OtaUrl http://192.168.1.97:8000/data/firmwares/tasmota.bin.gz` followed by another request setting `Upgrade 1`

On MQTT I can see the OtaURL being set but then I see

```json
{"Upgrade":"Failed File Not Found (404)"}
```

Which is strange as I can def curl the firmware at that endpoint both on my laptop and on another device on my LAN.

Can you think of anything that's going wrong?

**Comment by alexdelprete** [comment]
> This feels like it's something with my network but when I change to master it works so I'm super confused.

Let me understand: the master branch contains the same code of this PR and it works? I probably got it wrong, at least I hope so. :)

It's true that IT is not hard science...but there are some pretty solid foundations...:)

Explain me better so I can try to help you nail it...

**Comment by inverse** [comment]
master branch works just fine but I am trying to properly handle minimal firmware updates but also removing fetching that logic for the automatic path (since automatic is already beyond the need for minimal).

Thanks - I might reach out if I continue getting stuck :pray: 

It's often good to talk about it and then it'll probably become clear... this PR should make the updates nicer and than I can focus on some other features/improvements.

**Comment by alexdelprete** [comment]
> It's often good to talk about it and then it'll probably become clear...

I absolutely agree. Sometimes having a peer to discuss allows you to think more clearly. I'm sure you'll find the problem. If you need me for a quick talk, let me know, it's always a pleasure. :)

**Pull request merged**
