### PR TITLE
Add global result logline

### PR DESCRIPTION
**Pull request by inverse**
image

Add overview of update results to indicate success of update process

### CODE REVIEW

**Comment by alexdelprete** [comment]
Does it tell you at the end of the process which ones have failed? Matbe device # and name, if possible. :)

**Comment by inverse** [comment]
Not yet - I think I need to add more to that page though as right now it's only device ID  - More device info would be useful :D

**Comment by alexdelprete** [comment]
I would try to reuse the main page, since you have all the info there, you just need to add the UPDATE function and update the main page dynamically with maybe a new column with a checkmark for updates. :)

**Comment by inverse** [comment]
that whole page would need a rewrite to support that :D there's too much state change ajax happening...

**Comment by alexdelprete** [comment]
what a pity...:D

**Pull request merged**
